name: E2E Tests

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  e2e:
    name: E2E Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Install celestia-appd
        run: |
          curl -L https://raw.githubusercontent.com/celestiaorg/docs/main/public/celestia-app.sh | bash
          sudo mv /home/runner/celestia-app-temp/celestia-appd /usr/local/bin/

      - name: Install celestia node
        run: |
          curl -L https://raw.githubusercontent.com/celestiaorg/docs/main/public/celestia-node.sh | bash
          sudo mv /home/runner/celestia-node-temp/celestia /usr/local/bin/

      - name: Run E2E tests
        run: cargo test --all-targets --features e2e -- --test-threads=1